import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Liter } from "next/font/google"; // Import Liter

import "./globals.css";

import { Providers } from "./providers";

const liter = Liter({
  subsets: ["latin"],
  variable: "--font-liter",
  weight: "400"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={liter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/images/sb2.jpg')] bg-cover bg-center bg-fixed min-h-screen`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
